
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { RouteObject } from "react-router-dom";


import { UserGuard } from "app";


import { StackHandlerRoutes, LoginRedirect } from "app/auth";


import AdminDashboard from "./pages/AdminDashboard.tsx";
import App from "./pages/App.tsx";
import EmployeeDashboard from "./pages/EmployeeDashboard.tsx";

export const userRoutes: RouteObject[] = [

	{ path: "/auth/redirect", element: <LoginRedirect /> },
	{ path: "/auth/*", element: <StackHandlerRoutes /> },
	{ path: "/admin-dashboard", element: <UserGuard><AdminDashboard /></UserGuard> },
	{ path: "/admindashboard", element: <UserGuard><AdminDashboard /></UserGuard> },
	{ path: "/", element: <UserGuard><App /></UserGuard> },
	{ path: "/employee-dashboard", element: <UserGuard><EmployeeDashboard /></UserGuard> },
	{ path: "/employeedashboard", element: <UserGuard><EmployeeDashboard /></UserGuard> },

];
